module.exports={
    responseHandlerWithData:(res,code,message,data)=>{
        res.send({status:code,message,data});
    },
    responseHandlerWithDataPaginate:(res,code,message,page,limit,data)=>{
        res.send({status:code,message,data,page,limit});
    },
    responseHandlerWithDataExt:(res,code,message,data,avg,total,name)=>{
        res.send({status:code,message,total,data,name,avg});
    },
    responseHandlerWithmessage:(res,code,message)=>{
        res.send({status:code,message,});
    }
}